// <auto-generated />
using System;
using CityAnalytics.Storage;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CityAnalytics.Storage.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251013130905_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("CityAnalytics.Shared.DailyInstitutionUsage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BankCard")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Child")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("Free")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FullFare")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Institution")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Personnel")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SixtyYearsOld")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Student")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Teacher")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ticket")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Institution", "Date");

                    b.ToTable("DailyInstitutionUsages");
                });
#pragma warning restore 612, 618
        }
    }
}
